# Numpy

## Array Creation

In [1]:
import numpy as np
import math

In [5]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a, a.ndim

(array([[1, 2, 3],
        [4, 5, 6]]),
 2)

In [7]:
a.shape

(2, 3)

In [9]:
a.dtype

dtype('int32')

In [12]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
c = np.ones((2, 3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.random.rand(2, 3)


array([[0.18533168, 0.19961093, 0.00253975],
       [0.84693331, 0.97106603, 0.51039601]])

In [22]:
f = np.arange(10, 50, 2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [24]:
np.linspace(0, 2 , 15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [29]:
a = np.arange(10, 41, 10)
b = np.arange(1, 5)

c = a-b

d = a*b

c, d

(array([ 9, 18, 27, 36]), array([ 10,  40,  90, 160]))

In [33]:
farenheit = np.array([0, -10, -5, -15, 0])

celsius = (farenheit - 32)* 5/9
celsius

array([-17.77777778, -23.33333333, -20.55555556, -26.11111111,
       -17.77777778])

In [36]:
celsius > -20

array([ True, False, False, False,  True])

In [38]:
celsius % 2 == 0

array([False, False, False, False, False])

In [43]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A*B, A@B

(array([[2, 0],
        [0, 4]]),
 array([[5, 4],
        [3, 4]]))

In [46]:
b = np.arange(1, 16).reshape(3, 5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [51]:
a = np.arange(1, 5)
a[2]

3

In [54]:
a = np.arange(1, 7).reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [56]:
a[1, 1]

4

In [63]:
b = np.arange(1, 10)
b[[0, 3, 4]]

array([1, 4, 5])